name: "onnx_example"
platform: "onnxruntime_onnx"
max_batch_size : 8
input [
  {
    name: "input_0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 64, 64]
  }
]
output [
  {
    name: "output_0"
    data_type: TYPE_FP32
    dims: [ 5 ]
  }
]